:PROPERTIES:
:ID:       1720e4c4-62c3-4f52-9ca8-3b788c5e742d
:ROAM_REFS: https://zettelkasten.de/introduction/
:END:
#+title: characteristics of the zettelkasten
#+filetags: :notes:memory:

1. It's hyper-textual.

2. Your [[id:9d0a4d0d-065d-41e5-8fb4-fb49b5cdb5c4][zettelkasten]] is made of what we call a 'Zettel', which means a 'paper slip'.
   - a [[id:379a19e2-4229-481e-9355-b83b2e5239d4][zettel]] is the smallest building blocks of the Zettelkasten.
   - Zettelkasten  must follow the principle of atomicity, which means that each Zettel must contain only one thought 
   - the difference between your Zettelkasten and Wikipedia, is that Wikipedia links or references are for another article, 
     and here an article is not a thought.
   - your zettekasten must be a web of thoughts that connect and communicate with each other.
   - when each of your Zettels contain only one well defined thought, this will not make a room for guessing, 
    and the boundaries between thoughts will be well defined. [a Zettel per thought]

3. your Zettelkasten must be personal, it's your personal thinking tool.
   - the way you create your thought can be understaned only by you.
   - this might mean that there is no reason for sharing your notes with other, because the content of these notes is not comprehensible only by you.

