:PROPERTIES:
:ID:       162937f0-a915-48df-ab7b-12b82f96de43
:ROAM_REFS: cite:rawls-2009
:END:
#+title: civil religion in greeks and romans empires
Here 'Rawls, John' declare that in the past, in Greeks and Romans empires, the [[id:fc655056-aadf-4f78-a033-c36a58d3b8cd][religion]] had a civil nature.
which means that religious people had a loyalty towards the city, the group and the empire.
these communities developed a religion that serve this goal, in other words, a civil religion that direct their
golad toward city's prosperity. and provide to people a mean for unity.

We can expect that the nature of "religious teachings" will be directed to the concept of unity and how to build
a proper [[id:340ac669-a6f8-4a09-8ffb-d6e22421fe48][community]], and protect it.
"تقديس" for the king perhaps, a certain nature of morality to preserve the [[id:340ac669-a6f8-4a09-8ffb-d6e22421fe48][community]].
Traditions may serve the same goal. [[id:f49d30a5-bc87-47bf-835d-eac56506e46c][Marriage]] traditions for example.
#+begin_quote
And I have an opinion that may be somewhat new: that religion in the time of the Greeks and Romans was a civil religion,
where loyalty was to the city or to the empire, especially in times of wars and crises.
It was at their insistence, and more than that, that civil society was largely free
#+end_quote

