#+title: love and unconsciousness
#+roam_tags: love consciousness unconsciousness
i think that when we love someone, we love it unconsciousnessly due some qualities/small behavior this person might have, 
and then all the excuses that we provides is only our way to rationalize this choice.

because in reality, we don't know why we choosed this person in the first place, our unconsciousness who did that, not us, not our imaginary conscious self.

all the reasons that we provides to prove  why we love someone is only our escaping strategy so that we believe that we are in control, and our decision was rational, and our choices are our own.

that why i don't believe that there is some kind of a pool of qualities that we can describe or provide so that if someone fit in this qualities, we can know that he is the one.

we can love different persons with totally different personalities.

our unconsciousness is the responsible of this choice not us.

of course there is some kind of list that our unconsciousness choose from, but it is beyond our reach, and it changes over time,in a way we cannot predict or follow.

so if someone ask you about the qualities that your require in your future lover or something, consider this idea.

