:PROPERTIES:
:ID:       32ca542e-71ce-49af-92e6-8880465e874f
:ROAM_REFS: cite:huxley-1953-ends-means
:END:
#+title: violence as a way to change society
#+filetags: :violence:society:

According to [[id:b7f853e8-35cc-4330-8691-23528742a3ea][Aldous Huxley]],
Humans are committed to their traditions and what is familiar to them, and
they consider these traditions as a part of their identity.
So it's pointless to try to change these traditions through logic or any other
means, because they're not logically based.

As a result, the goal here is to change only the harmful traditions and use
these changes as a profit in order to build on it and create a regime capable of
developing in the direction that maximizes benefits.(change the big harmful ones !)
This will reduce the need for violence and weaken people's resistance to change.

It will also create a society that has a momentum into the right direction of change,
similar to fixing a ship's direction.

#+BEGIN_RTL
يقول ألدوس هكسلي :
أن العالم ليس هو المعقول كما يقول هيجل ، لكن بالواقع هنالك ما هو معقول ، وما هو غير ذلك .
ونظرا لميل البشر للتمسك بعاداتهم وتقاليدهم وإعتبارها (أو على الأقل أغلبها) جزءا من هويتهم لابد من التمسك بهذا
، لابد إذن أن نقلل ما يجب تغييره من هذه العادات إلى ما هو ضروري فقط ، وتجاهل تلك العادات التي لا تنفع ولا تضر .
الهدف هنا هو أن نغير من العادات والتقاليد الضارة ومحاولة خلق نظم قابلة للتطور في الإتجاه الذي يراه المصلح نافعا 
يهذا، تخف محاولة معارضة التغيير من طرف الجماهير ، وتقل الحاجة لإستخدام العنف
#+END_RTL

* Ref
End and Means: Chapter 4
