:PROPERTIES:
:ID:       3aa45c4d-a30d-49d9-823b-95f8ab31f1cc
:END:
#+title: Thinking, Fast and Slow
#+filetags: Building_a_Second_Brain brain talk google rationality

* Daniel Kahneman's talk on Talk at Google* 
[[https://www.youtube.com/channel/UCbmNph6atAoGfqLoCL_duAg][Talks at Google - YouTube]]
** About the Author
[[id:7ca2a718-95bf-4659-939f-b16eb5f45251][Daniel Kahneman]]: a Psychologist who won a noble prize for his work on ""
** Ideas
- there are 2 mode of thinking:
  when we see a picture of someone angry, we know immediately that he is angry.
  that type of thinking (intuition) feels like something that happen to us, not something that we do it.
  #+begin_example
  24 x 17 = .... 408
  #+end_example
  is an example of something we do it, it's hard, need us to remember and recall things.
  this type of thinking, requires a lot of ressources and with more ressources taken away, less will remain to other tasks.
  so, this type of thinking need focus and we shouldn't do it with other critical tasks.
- these 2 types of thinking, [[id:7ca2a718-95bf-4659-939f-b16eb5f45251][Daniel Kahneman]] calls them System 1 ( the fast one) and System 2
  #+begin_example
  x + y = 1.10
  x = y + 1
  ---------------
  (y + 1) + y = 1.10
  2y + 1  = 1.10 
  2y = 0.1 => y = 0.05 and x = 1.05
  #+end_example
- [[id:53cf335c-6454-4193-9913-9b0595f77029][Herbert Simon]] who was a psychologist then an economist and a political scientist and [[id:c17b039b-8d30-4061-900a-85e5ba676818][Nobel Prize]] laureate
  he gave a very good definition about what intuition is... it's simply "Recognition".
  there is no difference between a physician knowing or recognizing a disease and a little child learning and pointing to something and saying doggie.
  the little child has no idea what the clues are but he just said.
  - when you can trust intuition and when can't you?
    then come the issue of :
    is the world regular enough so that you can learn to recognize things?
    and then, did this particular individual one have an opportunity to learn the regulation of the world?.
- I can recognize my wife's mood from one word on the telephone for example ...etc, we are good intuition machines
- an intuitive expertise is not going to develop in a chaotic universe or in a chaotic world.
  for example you can't develop intuition in "the market or in poker game" (because they are not regular, don't have rules that helps us predict the next step/s)
  is the world not predictable?
- *Intuition =(included)=> System 1*
- so: intuition come from practicing and experience, but there are other types of intuitions that aren't from experience.
  where did they come from ?
  - in the [[id:51d0e033-d5fc-4785-abf5-843fb36f1557][honesty box]], someone glued posters and he changed the poster every week.
    the reaction decrease when there where eyes, big eyes looking at you, and increased when the poster contained flowers.
    the eyes give us the indication of being watched.
- system 1 is what happen in an associative memory, and associative memory is a gigantic network of ideas, and the ideas are linked to each other in various way
- an action effect/stimulus some ideas because these actions (some words for example) effect our associative memory and bring back some related ideas.
  after that we deal with these ideas in lllllllllll
  this should give you a sense of one of the functions of System1
*** Psychological Demonstration
photo for ABC and 12 13 14
- althought 13 and 13 are the same but you read them differently, because of the context.
2 things to consider here
- the Coherance
- You're not aware of the ambiguity.(the ambiguity is supressed).
- here a system (computer algo) may detect an ambiguity to decide if 13 is a B or 13.
"a male voice saying i believe i'm pregnant"
after system1's work, system2 work while you get surprised from the contradiction of the sentence.
- this system uses the world knowledge and use it to classify situations as normal or abnormal and it does that at top speed. updates very quickly.
- it updates what consider normal "it personal experience"
** Causal thinking 
which is more probable?
- that a mother has blue eyes if her daughter has blue eyes.
- that a daughter has blue eyes if her mother has blue eyes.
there is a probable _response_: that a daughter has blue eyes if her mother has blue eyes.
but statisticaly, they are equal.
but we _feel_ that the second is more probable and this feeling turned into a judgement of probability --> decision
** 
- people tend to have intuitions/judgments that they are not necessarily true
- this is a _theory_ how might this happen.
*** Substitution: How to jump to conclusion
- When a difficult judgment is required, and related judgment comes _easily_ to mind, the easy judgment is used instead.
people are often unaware of the substitution (here system1 work)
#+begin_comment
it's like that our brain prefer system1 to work all the time and find way to make it in charge.
#+end_comment
and our brain uses that conclusion to the wrong Question --> Bad decision.
- the substitution here is used for judgement and our judgement is not based on our experience, and they are much less likely to be correct than the intuition that do come from expertise, but they come with equal confidence.

- There are several mechanisms that take part in this _substitution_ thing.
**** the mental shotgun:
- when you asked to perform an operation, you typically perform other operations as well that are related to it associatevly , they are related to the target operation but they are different.
- if the first operation made us to computer more than we intend to compute, that allows for substitution to take place.
**** Question:
- How many dates did you have.
- What happiness means to you.
another great operation of _system1_
we can ma intensities across different dimensions.
 *standard example for this* : it's about julie who is a graduation senior and she read fluently when she was at age 4 and the question is:
 what's her GPA?
 the odd thing is that you know what her GPA is, at least you have an idea: about 3.7 or 3.6 ..etc
 but how people get to 3.7,3.6...etc
 well she read at age 4, that gives us an impression of precocity
 How precocious was she as a reader?
 people could express that in percentiles. 
 what is the likelihood that you could meet a child who would read faster that that? then you are asked a question about what is her *GPA*
 without you knowing it, you are matching the percentiles and you get the *GPA* that is about as extreme in the distribution of *GPA* as reading at age 4 is in the distribution of reading age, completely unaware.
 statistically, completely absurd 
 this is not the correct answer, but this is a compelling subjective answer.
 this is one of the mechanisms that leads to intuitive errors, this mechanism of substitution.

a lot of our mental life is conducted in just this way.
[[id:7ca2a718-95bf-4659-939f-b16eb5f45251][Daniel Kahneman]] said: let me complete the circle and talk a little bit about _subjective confidence_, (the probability of being correct)
it's actually not a judgment at all, it is a feeling that people have.
and the origin of this feeling (decision) is system1 assessing the fluency of its own processing.
assessing the story it has created to deal with current situation, and if the story is coherent, confidence is high.
but our brain can create coherent stories from very little information, and the coherence of the story depends very little on the quality and the quantity of the information, so people can be very confident with very little reason
confidence therefore is not a good diagnostic for when you can trust either yourself or somebody else.
*PS*: those 2 systems, they don't actually exist, but [[id:7ca2a718-95bf-4659-939f-b16eb5f45251][Daniel Kahneman]] used them for the sake of explanation.
but this may help you in creating personalities for these two systems, and this may help you or enable you to think better about psychological events, than if you were just had a long list of unrelated phenomena.

** Books to read(recommended from the author)
- moonwalking with einstein
  - a book of Joshua foer: How did he become a memory champianship of the USA
  - a fact knowen even for the Greeks, memory is terrible at remembering lists, but memory is superb at remembering routes through space -> use this with your [[id:b9045381-5ac6-468e-afe1-41abea75767a][BASB]]
  - evolution did that
  - so to remember lists, list the list items in a mental routes.
** Questions and Thoughts  
- what makes the ideas related to each other in your mind.
- which type of links our mind use to link the ideas together.
- is related ideas are located in the same region of the memory, so that when an action stimulus and idea, it effect its neighbors???
- What's the woman's feeling during pregnancy and when she get birth to her child?.

