#+title: metadata and empty file in linux
#+roam_tags: linux metadata inode size
when you create a file without any data in it by[[file:20210112111033-touch_command.org][ touch command]]  for example.
~touch myfile~
~ls -l /tmp/myfile~
you'll get a file with a size == ~0 bytes~.

but why?, is'nt there a name and some data related to this file, so the size of the file must be bigger than ~0 bytes~.

actually these data are called ~metadata~ and are not saved on the file itself, but it depends on the filesystem you use.

so for example, if you are using [[file:20210112111835-ext4_filesystem.org][ext4 filesystem]]  for example, these metadata will be stored in the [[file:20210112111942-inode.org][Inode]] of the file.

you can see all the inodes availlable and used on each partition in your system, by invoking the following command:
~df -i~ 
or for more human readable format use the ~-h~ option: 
~df -hi~

#+begin_example
  Filesystem     Inodes IUsed IFree IUse% Mounted on
  dev              475K   544  475K    1% /dev
  run              477K   722  476K    1% /run
  /dev/sda1         15M  246K   15M    2% /
  shm              477K     1  477K    1% /dev/shm
  cgroup_root      477K    16  477K    1% /sys/fs/cgroup
  /dev/sda2        5.8M  221K  5.5M    4% /home
  /dev/sda6           0     0     0     - /boot
  tmpfs            477K    23  477K    1% /run/user/1000
  /dev/sda4         42M   34K   42M    1% /media/Works
  /dev/sda3         11M  2.8K   11M    1% /media/FUN
#+end_example
and the number of the[[file:20210112111942-inode.org][ Inodes]] you have left will decide how many files you can create in future on this perticular partition.
