:PROPERTIES:
:ID:       927218c9-9268-492f-befe-b748446288ed
:END:
#+title: individualism,freedom and suffering
#+filetags: :choice:lust:modern:suffering:freedom:

- Individualism gives people a lot of freedom, but it also gives them a lot of confusion.
- When there are more possibilities in front of us, making a decision gets more difficult.

Take marriage as an example

In a book by Alain de Botton, he says that: "in the old days, when we had no choice but to marry our neighbor's daughter since she was the only girl accessible in the neighborhood, and such a young guy had not seen another girl, nor a more beautiful girl, he did not feel deprived (حرم) of anything."

contrary to what we see nowadays, the first problem that may occur between two persons in a relationship, one or both of them may consider the possibility of finding a better person, which will only increase suffering even more

Sometimes, happiness is a choice , constructed by awareness 

One of the things that make [[id:b5cd910d-2f38-443c-adc2-cb0b3b040177][the paradox of choice]] occur, is that we don't know what we want in front, and don't know our needs, because we don't understand ourselves.

For me, abundance does not have to be physical; simply knowing that there are other options and that you have the ability to reach these choices is enough; as they say, it just takes more effort to get there, which will lead to a sense of guilt with every decision you make, because you will feel completely responsible, and this will lead to more suffering.

- I think that there is a relation to the middle-age crisis
